import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {createProviders,confirmedMemory} from '../integrations/providers.js';import {handle} from '../integrations/mcp-server.js';import {searchKnowledge,KNOWLEDGE,PLAYBOOKS} from '../knowledge.js';import {analyzeIntent} from '../intent.js';import {freshInterview,modelPayload} from '../interview.js';
test('bundled knowledge spans every stage, preserves citations and abstains on no match',()=>{assert.equal(KNOWLEDGE.length,15);assert.deepEqual(searchKnowledge('xyzunknown'),[]);assert.ok(searchKnowledge('报价')[0].sources.length);const s=freshInterview();s.answers.role='审单主管';const p=JSON.parse(modelPayload(s,'?').messages[1].content);assert.ok(p.knowledge.length);assert.equal(p.playbooks.length,3);assert.equal(p.intentExamples.public.length,12);});
test('public excerpts retain train provenance, separate licenses and synthetic identity',async()=>{for(const name of ['clinc','sgd']){const rows=JSON.parse(await readFile(new URL('../data/'+name+'-sample.json',import.meta.url)));assert.ok(rows.length);assert.ok(rows.every(r=>r.source===name&&['train','oos_train'].includes(r.split)));assert.ok((await readFile(new URL('../data/licenses/'+name+'.txt',import.meta.url),'utf8')).includes('Attribution'));}const rows=JSON.parse(await readFile(new URL('../data/home-intents.json',import.meta.url)));assert.ok(rows.every(r=>r.realUser===false));});
test('intent hints never authorize and preserve correction and negative boundaries',()=>{const a=analyzeIntent('不是销售，我负责审单。不要自动下单');assert.ok(a.hints.some(x=>x.label==='correction'));assert.ok(a.hints.some(x=>x.label==='boundary'));assert.equal(a.authorization,false);assert.equal(analyzeIntent('可以').authorization,false);assert.equal(analyzeIntent('???').unknown,true);});
test('unconfigured providers make no network calls',async()=>{const p=createProviders({},()=>{throw Error('network called');});assert.equal((await p.knowledge('报价')).status,'not_configured');assert.equal((await p.memory('岗位')).status,'not_configured');});
test('provider requests use configured KB and fixed memory scope, filtering foreign results',async()=>{const calls=[];const scope='viking://user/alice/memories';const p=createProviders({WEKNORA_URL:'https://knowledge.example',WEKNORA_KEY:'test',WEKNORA_KB:'kb-fixed',OPENVIKING_URL:'https://memory.example',OPENVIKING_KEY:'test2',OPENVIKING_MEMORY_URI:scope},async(url,opts)=>{calls.push([String(url),opts]);return new Response(JSON.stringify(String(url).includes('knowledge-search')?{success:true,data:[{id:'1',content:'test',knowledge_title:'规则'}]}:{status:'ok',result:{memories:[{uri:scope+'/role',abstract:'主管'},{uri:'viking://user/bob/memories/role'}]}}));});assert.equal((await p.knowledge('报价')).items[0].source,'规则');assert.equal(JSON.parse(calls[0][1].body).knowledge_base_id,'kb-fixed');assert.equal(calls[0][1].redirect,'error');assert.equal((await p.memory('岗位')).items.length,1);assert.equal(JSON.parse(calls[1][1].body).target_uri,scope);});
test('memory confirmation contract requires explicit provenance, no implicit write',()=>{assert.throws(()=>confirmedMemory({userId:'u',key:'role',value:'主管'}));assert.equal(confirmedMemory({userId:'u',key:'role',value:'主管',source:'访谈1用户确认',confirmedAt:'2026-09-20T00:00:00Z'}).status,'confirmed');assert.equal(createProviders({}).status().memoryWrite,false);});
test('MCP initialization and read-only tools reject unknown or write arguments',async()=>{const p=createProviders({});const init=await handle({id:1,method:'initialize'});assert.equal(init.result.protocolVersion,'2025-11-25');assert.equal(await handle({method:'notifications/initialized'}),null);const list=await handle({id:2,method:'tools/list'});assert.equal(list.result.tools.length,4);assert.ok(list.result.tools.every(t=>t.annotations.readOnlyHint));assert.equal((await handle({id:3,method:'tools/call',params:{name:'memory_search',arguments:{query:'role',userId:'bob'}}},p)).error.code,-32602);const r=await handle({id:4,method:'tools/call',params:{name:'skills_list'}},p);assert.equal(r.result.structuredContent.skills.length,PLAYBOOKS.length);});
