import test from 'node:test';
import assert from 'node:assert/strict';
import {STAGES} from '../core.js';
import {freshInterview,candidates,record,followupQuestion,assessment,valueEstimate,judge,report,reportMarkdown,validateReply,modelPayload,invalidate} from '../interview.js';
const review=STAGES.find(x=>x.id==='review');
function ready(){const s=freshInterview();s.selected='review';s.answers={role:'审单主管',idea:'AI检查订单和报价'};const a=assessment(s);a.checks={data:'yes',rules:'yes',review:'yes',access:'yes',evidence:'yes'};a.numbers={volume:200,before:25,after:10,coverage:80,hourly:60,cash:50,cost:300,setup:1000};return s;}
test('interview routes by actual role and ideas, full 15-stage catalog remains available',()=>{const s=ready();assert.equal(candidates(s)[0].id,'review');assert.equal(STAGES.length,15);assert.match(followupQuestion(s).text,/订单号/);s.answers={role:'售后服务主管',idea:'售后投诉维修工单归类'};assert.equal(candidates(s)[0].id,'service');});
test('changes invalidate acceptance and record rounds without rewriting answers',()=>{const s=ready();s.accepted=true;record(s,{id:'idea',text:'想做什么？'},'先做离线审单');assert.equal(s.accepted,false);assert.equal(s.answers.idea,'先做离线审单');assert.equal(s.history[0].round,1);});
test('unknown numeric inputs never become zero; invalid percentages and negatives rejected',()=>{assert.equal(valueEstimate({}).complete,false);assert.ok(valueEstimate({volume:1,before:-1}).error);assert.ok(valueEstimate({coverage:101}).error);assert.ok(valueEstimate({cash:Infinity}).error);});
test('time vs cash and added labor are correctly distinguished',()=>{const s=ready(),a=assessment(s);let v=valueEstimate(a.numbers);assert.equal(v.hours,40);assert.equal(v.net,900);a.numbers.cash=0;v=valueEstimate(a.numbers);assert.equal(v.net,-300);a.numbers.cost=0;v=valueEstimate(a.numbers);assert.equal(v.net,0);assert.equal(judge(s,review).grade,'A');a.numbers.after=30;assert.equal(valueEstimate(a.numbers).net,-800);});
test('grade gates distinguish missing evidence, infeasible control, negative value and verified value target',()=>{const s=ready(),a=assessment(s);assert.equal(judge(s,review).grade,'A');a.checks.data='unknown';assert.equal(judge(s,review).grade,'B');a.checks.data='yes';a.checks.review='no';assert.equal(judge(s,review).grade,'D');a.checks.review='yes';a.numbers.after=30;assert.equal(judge(s,review).grade,'C');a.numbers.after=10;a.source='measured';a.target=30;assert.equal(judge(s,review).grade,'A');s.documents=[{id:'d',name:'样本',chunks:[{text:'审单必须核对订单号和版本',location:'第1行'}]}];assert.equal(judge(s,review).grade,'S');a.target=45;assert.equal(judge(s,review).grade,'A');a.checks.access='no';assert.equal(judge(s,review).grade,'C');});
test('one-screen report is bounded and user amendments take effect',()=>{const s=ready(),a=assessment(s);a.goal='目标'.repeat(200);a.action='用户自己的处理动作，最后交给主管复核';const r=report(s);assert.ok(r.rows.reduce((n,x)=>n+x[1].length,0)<=406);assert.equal(r.rows[1][1],a.action);assert.match(reportMarkdown(s),/讨论稿/);s.accepted=true;assert.match(reportMarkdown(s),/用户已确认/);invalidate(s);assert.equal(report(s).accepted,false);});
test('model evidence is checked against exact source and cannot create accepted decisions',()=>{const s=ready();s.documents=[{id:'d',name:'订单',chunks:[{text:'审单必须核对订单号和版本',location:'行2'}]}];const r=validateReply({summary:'推断',question:'谁复核？',findings:[{stageId:'review',sourceId:'d',quote:'审单必须核对订单号和版本',observation:'相关'},{stageId:'review',sourceId:'fake',quote:'审单必须核对订单号和版本'},{stageId:'unknown'}]},s);assert.equal(r.findings.length,2);assert.equal(r.findings[0].verified,true);assert.equal(r.findings[1].verified,false);assert.equal(s.accepted,false);assert.throws(()=>validateReply({summary:'缺少问题字段'},s));});
test('model context includes industry, skills, outputs and real materials with bounded excerpts',()=>{const s=ready();s.documents=[{id:'d',name:'大文件',chunks:[{text:'字'.repeat(70000)}]}];const p=modelPayload(s,'追问');const body=JSON.parse(p.messages[1].content);assert.equal(body.documents[0].chunks[0].text.length,60000);assert.equal(body.industry.length,7);assert.equal(body.scenarios.length,15);assert.equal(body.answers.role,'审单主管');});
