import {STAGES,evidenceFor,safeEndpoint} from './core.js';
import {SOURCES,RESEARCH_DATE} from './industry.js';
import {parseFile,textChunks} from './parsers.js';
import {QUESTIONS,CHECKS,NUMBERS,GRADES,freshInterview,record,invalidate,candidates,currentStage,assessment,followupQuestion,valueEstimate,judge,report,reportMarkdown,routeFor,modelPayload,validateReply} from './interview.js';
const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='home-ai-interview-v2';
let state=freshInterview(),beforeDemo=null,busy=false,connection=null,requestController=null;
const status=t=>{$('#status').textContent=t;};
const closeDialogs=()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close());
const uid=()=>globalThis.crypto?.randomUUID?.()||'doc-'+Date.now()+'-'+Math.random().toString(36).slice(2);
function question(){
 if(state.phase==='interview')return QUESTIONS[state.index];
 if(state.phase==='clarify')return state.pending||(state.pending=followupQuestion(state));
 if(state.phase==='refine')return {...QUESTIONS.find(q=>q.id===state.editField),section:'再聊一轮',hint:'请补充或修正这一项。原有内容已放在输入框中，可直接编辑。'};
 if(state.phase==='scene'){const stage=currentStage(state),check=CHECKS[state.sceneStep];return {text:check.text(stage),hint:'先选择实际状态，再用自己的话说明依据；不清楚可以保留待确认。',section:`深入场景 · ${state.sceneStep+1} / 4`,check};}
 return null;
}
function render(){
 const phase=state.phase,isReport=phase==='report';document.body.classList.toggle('compact-intro',state.history.length>0||phase!=='interview');document.body.classList.toggle('report-mode',isReport);
 $('#demo-banner').hidden=!state.demo;$('#mode-label').textContent=connection?'AI辅助访谈 · '+connection.model:'本地引导 · 无需密钥';$('#round-label').textContent=`第 ${state.round} 轮`;
 const step=phase==='interview'?(state.index<2?0:state.index<6?1:2):['clarify','profile','refine'].includes(phase)?1:['candidates','scene','value'].includes(phase)?2:3;
 document.querySelectorAll('[data-step]').forEach(e=>e.classList.toggle('active',Number(e.dataset.step)<=step));
 if(question())renderQuestion();else if(phase==='profile')renderProfileCheck();else if(phase==='candidates')renderCandidates();else if(phase==='value')renderValue();else if(phase==='report')renderReport();
 $('#workspace').querySelectorAll('button').forEach(b=>{if(busy)b.disabled=true;});
}
function renderQuestion(){const q=question(),last=state.history.at(-1);let input='';
 if(state.phase==='refine')input=state.answers[state.editField]||'';
 const a=state.phase==='scene'?assessment(state):null;const check=q.check;
 $('#workspace').innerHTML=`<article class="card">
 <div class="question-top"><span class="avatar" aria-hidden="true">✳</span><span class="kicker">${esc(q.section||'把不清楚的地方，再聊清楚')}</span></div>
 ${last&&state.phase==='clarify'?`<div class="last-answer"><strong>您的最新补充</strong>${esc(last.answer.slice(0,160))}</div>`:''}
 ${state.ai&&state.phase==='clarify'?`<p class="hint">AI的理解（请核实）：${esc(state.ai.summary)}</p>`:''}
 ${state.phase==='refine'?`<label class="refine-select">这次重点聊什么<select id="edit-field">${QUESTIONS.map(x=>`<option value="${x.id}" ${x.id===state.editField?'selected':''}>${x.label}</option>`).join('')}</select></label>`:''}
 <h2 id="question-title">${esc(q.text)}</h2><p class="hint">${esc(q.hint||'')}</p>
 ${check?`<div class="checks" role="group" aria-label="条件状态">${[['yes',check.yes],['no',check.no],['unknown','暂不清楚']].map(([v,t])=>`<button class="chip ${a.checks[check.id]===v?'selected':''}" data-check="${v}" aria-pressed="${a.checks[check.id]===v}">${esc(t)}</button>`).join('')}</div>`:''}
 ${q.chips?`<div class="chips">${q.chips.map(t=>`<button class="chip" data-example="${esc(t)}">${esc(t)}</button>`).join('')}</div>`:''}
 <form id="answer-form"><div class="answer-box"><textarea id="answer" aria-labelledby="question-title" maxlength="5000" placeholder="像和同事聊天一样，说说您的实际情况……" rows="4">${esc(input||(check?a.notes[check.id]||'':''))}</textarea></div>
 <div class="actions"><button type="button" id="attach-button" class="text-button">＋ 提供材料${state.documents.length?'（'+state.documents.length+'）':''}</button><button type="button" id="skip-button" class="text-button push">暂不清楚</button><button type="submit" class="primary" id="send-answer">${busy?'正在思考…':state.phase==='clarify'?'记录并梳理画像':'继续聊 →'}</button></div></form>
 ${state.phase==='interview'&&state.index===0?'<p class="muted" style="margin:18px 0 0;font-size:11px">一次只聊一个重点。途中可补材料、修正回答，也可以暂时跳过。</p>':''}
 </article>`;
 $('#answer-form').onsubmit=e=>{e.preventDefault();submitAnswer();};$('#skip-button').onclick=()=>submitAnswer(true);$('#attach-button').onclick=openMaterials;
 document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{$('#answer').value=b.dataset.example+'，';$('#answer').focus();});
 document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{a.checks[check.id]=b.dataset.check;invalidate(state);document.querySelectorAll('[data-check]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});});
 if($('#edit-field'))$('#edit-field').onchange=e=>{state.editField=e.target.value;render();};
}
async function submitAnswer(skip=false){
 if(busy)return;const q=question(),answer=skip?'暂不清楚':$('#answer').value.trim();if(!answer){status('请说说实际情况，或选择“暂不清楚”。');return;}
 status('');const phase=state.phase,activeState=state;
 if(phase==='scene'){
 const a=assessment(state);if(skip)a.checks[q.check.id]='unknown';if(!a.checks[q.check.id]){status('请先选择这个条件是否具备，再说明依据。');return;}a.notes[q.check.id]=answer;record(state,{text:q.text},answer);state.sceneStep++;state.phase=state.sceneStep<CHECKS.length?'scene':'value';render();return;
 }
 record(state,q,answer);
 if(phase==='interview'){
 state.index++;if(state.index>=QUESTIONS.length){state.phase='clarify';state.pending=null;}
 }else if(phase==='clarify'){state.phase='profile';state.pending=null;}
 else if(phase==='refine'){state.round++;state.profileConfirmed=false;for(const a of Object.values(state.scenes)){a.checks={};}state.phase='clarify';state.pending=null;}
 if(connection&&phase!=='clarify'){
 const reply=await askModel(q.text);
 if(state!==activeState)return;
 if(reply?.question){state.resume={phase:state.phase,index:state.index};state.phase='clarify';state.pending={text:reply.question,hint:'结合您的回答和材料，进一步确认这一点。'};}
 }
 if(phase==='clarify'&&state.resume){state.phase=state.resume.phase;state.index=state.resume.index;state.resume=null;}
 render();
}
function profileRows(editable=true){return QUESTIONS.map(q=>`<div class="profile-row"><strong>${esc(q.label)}</strong><p>${esc(state.answers[q.id]||'尚未了解')}</p>${editable?`<button class="text-button" data-edit="${q.id}">补充 / 修正</button>`:''}</div>`).join('');}
function bindEdits(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{closeDialogs();beginRefine(b.dataset.edit);});}
function renderProfileCheck(){
 const unknown=QUESTIONS.filter(q=>!state.answers[q.id]||state.answers[q.id]==='暂不清楚');
 $('#workspace').innerHTML=`<article class="card"><p class="kicker">先对齐理解，再给建议</p><h2>这是我们目前了解的您。</h2><p class="hint">请核对岗位与目标。${unknown.length?'仍有 '+unknown.length+' 项待明确，候选场景会保留这些缺口。':'接下来把您的想法拆成可以试做的动作。'}</p><div class="profile-row"><strong>组织位置与岗位</strong><p>${esc(state.answers.role||'待确认')}</p></div><div class="profile-row"><strong>您希望AI帮忙的事</strong><p>${esc(state.answers.idea||'待确认')}</p></div><div class="profile-row"><strong>期待的结果</strong><p>${esc(state.answers.success||'待确认')}</p></div><details><summary>展开完整岗位画像与最新澄清</summary>${profileRows()}${state.followups.slice(-4).map(f=>`<div class="profile-row"><strong>${esc(f.question)}</strong><p>${esc(f.answer)}</p></div>`).join('')}</details><div class="actions"><button id="refine-button">还想补充</button><button id="confirm-profile" class="primary push">画像已核对，找机会 →</button></div></article>`;
 bindEdits();$('#refine-button').onclick=()=>beginRefine();$('#confirm-profile').onclick=()=>{state.profileConfirmed=true;state.phase='candidates';render();};
}
function renderCandidates(){
 const list=candidates(state);const found=list.some(x=>x.match>0);
 $('#workspace').innerHTML=`<article class="card"><p class="kicker">从想法，到可执行的动作</p><h2>这几个场景，值得继续聊。</h2><p class="hint">${found?'按您的岗位、工作与AI想法匹配，以下是初步候选。':'目前还不足以定位岗位，先列出三个讨论样例，也可手动选择其他环节。'}逐个核实条件、算清价值，再决定优先级。</p>${list.map(sceneCard).join('')}
 <details><summary>查看全链条其他场景（15个环节）</summary><label>选择与您更相关的环节<select id="all-stages">${STAGES.map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.title)}</option>`).join('')}</select></label><button id="choose-other">深入这个场景</button></details>
 <details><summary>等级怎么判断？</summary><div class="grade-key"><p>超级适合且价值明显：条件齐备、相关样本、用户标记实测、达到其工时目标且现金净收益为正。</p><p>A：条件齐备且预计节省工时，仍需验证。B：有潜力但存在缺口。C：当前价值或实施条件不足。D：当前方式无法复核、无法控制错误。</p><p>这是解释性试点筛选，不是行业认证；缺信息时保留B及缺口，不把未知当作不适合。</p></div></details><div class="actions"><button id="refine-button" class="text-button">这些不贴切？继续沟通</button><button id="model-insight" class="text-button push">请 AI 综合分析</button></div></article>`;
 document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>startScene(b.dataset.scene));$('#choose-other').onclick=()=>startScene($('#all-stages').value);$('#refine-button').onclick=()=>beginRefine();$('#model-insight').onclick=async()=>{if(!connection){openModel();return;}const reply=await askModel('结合完整岗位画像、用户自己的想法与材料，比较多个适合AI的具体动作，指出关键不清晰处并追问。');if(reply){state.phase='clarify';state.pending={text:reply.question||'这些分析与您的实际工作相符吗？有哪些需要纠正？',hint:'先对齐模型的理解，再回到场景比较。'};render();}};
}
function sceneCard(stage){const j=judge(state,stage),e=evidenceFor(stage,state.documents),a=assessment(state,stage.id),model=state.ai?.findings.filter(f=>f.stageId===stage.id)||[];
 return `<section class="scene"><span class="badge ${j.grade}">${esc(GRADES[j.grade])}</span><h3>${esc(a.customTitle||stage.title)}</h3><p>${esc(stage.action)}</p><p><strong>价值：</strong>${esc(j.value.text||j.value.error||'待测算')}</p><p class="muted"><strong>判断依据：</strong>${esc(j.reason)}</p><details><summary>看条件、证据与技术路线</summary><p>输入：${esc(stage.input)}。输出：${esc(stage.output)}。</p><p>人工：${esc(stage.verify)}。</p><p>边界：${esc(stage.risk)}。</p><p>技术路线：${esc(routeFor(stage.id))}。</p>${e.length?e.map(x=>`<p class="evidence">${esc(x.source)} / ${esc(x.location)}：${esc(x.quote)}<br>仅表示材料相关，需核实版本和代表性。</p>`).join(''):'<p>尚未发现相关材料；请提供样本进一步判断。</p>'}${model.map(f=>`<p class="evidence">AI辅助建议：${esc(f.observation)} ${esc(f.recommendation)}<br>${f.verified?'引文已核对：'+esc(f.source)+' / '+esc(f.location)+' '+esc(f.quote):'无可核对原文，需人工验证'}</p>`).join('')}</details><button data-scene="${stage.id}">${a.numbers.volume!==undefined?'继续完善与查看报告':'聊聊条件，测算价值'} →</button></section>`;
}
function startScene(id){if(!STAGES.some(x=>x.id===id))return;invalidate(state);state.selected=id;state.sceneStep=0;state.phase='scene';render();}
function renderValue(){const s=currentStage(state),a=assessment(state);
 $('#workspace').innerHTML=`<article class="card"><p class="kicker">${esc(s.name)} · 算一笔明白账</p><h2>它能给您带来多少价值？</h2><p class="hint">只填写这个场景的任务。使用后耗时要含准备、等待、处理与人工复核。不了解的数字留空，先去采样。</p><div class="number-grid">${NUMBERS.slice(0,4).map(numberInput).join('')}</div><details><summary>进一步核算现金收益与投入</summary><p class="hint">空出的工时不一定减少工资支出。只有可兑现比例对应现金节约；不涉及的费用请明确填0。</p><div class="number-grid">${NUMBERS.slice(4).map(numberInput).join('')}</div></details><label>以上数字的依据<select id="value-source"><option value="estimate" ${a.source==='estimate'?'selected':''}>个人估计 / 目标假设，尚未验证</option><option value="measured" ${a.source==='measured'?'selected':''}>来自实际记录或对照试验（请补材料说明）</option></select></label><label>您认为值得做的最低节省工时（小时/月，可留空）<input id="value-target" type="number" min="0" max="1000000000" value="${esc(a.target)}"></label><label class="checkline"><input type="checkbox" id="evidence-check" ${a.checks.evidence==='yes'?'checked':''}><span>我确认所提供材料与本场景有关，数字来源、口径和样本代表性已核对。</span></label><div id="value-result" class="value-result" role="status"></div><details><summary>计算方法与局限</summary><p class="hint">月净工时＝月任务量×覆盖率×（原耗时−使用后总耗时）÷60。月净现金收益＝正的工时价值×可兑现比例−月费用；增加的工时按全额人工成本扣除。静态回本＝一次投入÷正的月净收益。质量和增收目标暂列验收指标，不自动折算收入；多个场景可能共享收益，不可直接相加。</p></details><div class="actions"><button id="back-candidates">比较其他场景</button><button id="to-report" class="primary push">形成一屏讨论稿 →</button></div></article>`;
 function update(){const v=valueEstimate(a.numbers);$('#value-result').textContent=v.error||v.text;if(v.payback!==undefined&&v.money)$('#value-result').textContent+=v.payback===null?'；当前假设不回本':`；静态回本 ${v.payback.toFixed(1)} 个月`;}
 document.querySelectorAll('[data-number]').forEach(e=>e.oninput=()=>{a.numbers[e.dataset.number]=e.value;invalidate(state);update();});$('#value-source').onchange=e=>{a.source=e.target.value;invalidate(state);};$('#value-target').oninput=e=>{a.target=e.target.value;invalidate(state);};$('#evidence-check').onchange=e=>{a.checks.evidence=e.target.checked?'yes':'unknown';invalidate(state);};
 $('#back-candidates').onclick=()=>{state.phase='candidates';render();};$('#to-report').onclick=()=>{if(valueEstimate(a.numbers).error){status(valueEstimate(a.numbers).error);return;}state.phase='report';status('');render();};update();
 function numberInput([k,label]){return `<label>${esc(label)}<input data-number="${k}" type="number" min="0" max="${['coverage','cash'].includes(k)?100:1000000000}" step="any" inputmode="decimal" value="${esc(a.numbers[k]??'')}" placeholder="待确认"></label>`;}
}
function renderReport(){const r=report(state),a=assessment(state),j=judge(state,currentStage(state));
 $('#workspace').innerHTML=`<article class="report-card" id="one-screen-report"><div class="report-top"><span>家居 AI · ${state.demo?'虚构示例 · ':''}一屏行动报告</span><span>${state.accepted?'用户已确认可行':'讨论稿 · 待您确认'}</span></div><h2>${esc(r.title)}</h2><span class="badge ${j.grade}">${esc(r.grade)}</span><div class="report-rows">${r.rows.map(([k,v])=>`<div class="report-row"><strong>${esc(k)}</strong><span>${esc(v)}</span></div>`).join('')}</div><p class="report-foot">第${state.round}轮 · ${state.accepted?'按以上条件试点，效果以实际验收为准':'请修正不贴切的地方，再确认是否愿意试点'} · ${new Date().toLocaleDateString('zh-CN')}</p></article>
 <div class="report-controls">${!state.accepted?`<details><summary>修订报告的目标、条件与实施方式</summary><div class="card">${[['customTitle','场景名称',26,r.title],['action','人机协作动作（含人工复核）',82,a.action||r.rows[1][1]],['goal','您的具体目标',50,a.goal||state.answers.idea||''],['metric','验收指标与目标值',35,a.metric||currentStage(state).metric],['conditions','必要条件',70,a.conditions||r.rows[3][1]],['form','应用形式',46,a.form||r.rows[4][1]],['route','技术路线',65,a.route||routeFor(state.selected)]].map(([k,l,m,v])=>`<label>${l}<textarea data-report-field="${k}" maxlength="${m}" rows="2">${esc(v.slice(0,m))}</textarea></label>`).join('')}<button id="apply-report" class="primary">应用修订</button></div></details><label class="checkline"><input id="accept-check" type="checkbox"><span>我认可这个场景、必要条件、价值假设与验收方式，认为可以据此试点。</span></label>`:''}</div>
 <div class="actions report-actions"><button id="refine-button">继续沟通</button><button id="recalculate">重算价值</button>${state.accepted?'<button id="download-report" class="primary push">下载一屏报告</button>':'<button id="accept-report" class="primary push">确认可行</button>'}</div><div class="actions report-actions"><button id="compare-button" class="text-button">比较多个场景</button><button id="download-draft" class="text-button">下载${state.accepted?'报告':'讨论稿'}</button><button id="print-report" class="text-button">打印</button></div>`;
 $('#refine-button').onclick=()=>beginRefine();$('#recalculate').onclick=()=>{invalidate(state);state.phase='value';render();};$('#compare-button').onclick=()=>{state.phase='candidates';render();};$('#download-draft').onclick=downloadReport;$('#print-report').onclick=()=>window.print();if($('#download-report'))$('#download-report').onclick=downloadReport;
 if($('#apply-report'))$('#apply-report').onclick=()=>{document.querySelectorAll('[data-report-field]').forEach(e=>a[e.dataset.reportField]=e.value.trim());invalidate(state);render();status('讨论稿已更新，请重新核对后确认。');};
 if($('#accept-report'))$('#accept-report').onclick=()=>{
 if(!$('#accept-check').checked){status('请先核对报告，并勾选您对可行性的确认。');return;}
 if(!CHECKS.every(c=>a.checks[c.id]==='yes')||!j.value.complete||['C','D'].includes(j.grade)){status('目前还有未具备的条件或未完成的价值测算。可先下载讨论稿，继续沟通或重算价值后再确认可行。');return;}
 state.accepted=true;status('已记录您的确认。后续修改条件或数据时，需要重新确认。');render();};
}
function beginRefine(field='idea'){invalidate(state);state.phase='refine';state.editField=field;state.resume=null;status('');render();}
function openProfile(){$('#profile-content').innerHTML=profileRows()+`<details><summary>访谈记录（${state.history.length}条）</summary>${state.history.map(x=>`<div class="history-item"><p class="muted">第${x.round}轮 · ${esc(x.question)}</p><p>${esc(x.answer)}</p></div>`).join('')||'<p>还没有回答。</p>'}</details>`;bindEdits();$('#profile-dialog').showModal();}
function openMaterials(){renderDocuments();$('#material-dialog').showModal();}
function materialChanged(){const draft=$('#answer')?.value;invalidate(state);state.ai=null;for(const a of Object.values(state.scenes))a.checks.evidence='unknown';renderDocuments();render();if(draft!==undefined&&$('#answer'))$('#answer').value=draft;}
function renderDocuments(){$('#documents').innerHTML=state.documents.map(d=>`<article class="doc"><strong>${esc(d.name)}</strong><p>${d.chunks.length}条摘录 · ${esc((d.warnings||[]).join(' '))}</p><details><summary>查看提取的文字</summary><p class="evidence">${d.chunks.slice(0,8).map(c=>esc(c.location)+'：'+esc(c.text)).join('<br>')}</p></details><button data-delete-doc="${esc(d.id)}">移除</button></article>`).join('');document.querySelectorAll('[data-delete-doc]').forEach(b=>b.onclick=()=>{state.documents=state.documents.filter(d=>d.id!==b.dataset.deleteDoc);materialChanged();});}
async function addFiles(files){for(const file of files){try{if(state.documents.length>=8)throw Error('最多8份材料，请先移除不需要的文件。');$('#material-status').textContent='正在读取 '+file.name;const result=await parseFile(file);state.documents.push({...result,id:uid(),name:file.name});materialChanged();$('#material-status').textContent='已在本页读取 '+file.name+'。';}catch(e){$('#material-status').textContent=e.message;break;}}$('#file-input').value='';}
function openSources(){$('#sources-content').innerHTML=`<p class="muted">公开来源核查：${RESEARCH_DATE}。行业数据只作背景，不代替企业价值测算。标准网页仅核验元数据与官方介绍，具体条款需使用适用的正式文本。</p><p>这些资料转化为访谈中的订单与版本追溯、尺寸确认、工艺约束、质量验收、成本口径等问题。追问是本工具的分析，不是标准条文。</p>${SOURCES.map(s=>`<article class="source"><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a><p>${esc(s.text)}</p></article>`).join('')}<p class="muted" style="margin-top:16px">产业链覆盖：${STAGES.map(x=>x.name).join('、')}。行为与经济审计贯穿全部环节。</p>`;$('#sources-dialog').showModal();}
function openModel(){$('#payload-preview').textContent=JSON.stringify(modelPayload(state,question()?.text||'综合分析'),null,2);$('#model-dialog').showModal();}
async function askModel(q){
 if(!connection||busy)return null;busy=true;render();status('AI正在结合访谈与材料思考…');const snapshot=connection,activeState=state,revision=state.revision;requestController=new AbortController();const timer=setTimeout(()=>requestController?.abort(),90000);
 try{const payload=modelPayload(state,q);const r=await fetch(snapshot.endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(snapshot.key?{Authorization:'Bearer '+snapshot.key}:{})},body:JSON.stringify({...payload,model:snapshot.model}),signal:requestController.signal,credentials:'omit',redirect:'error'});if(!r.ok)throw Error('模型服务返回 HTTP '+r.status);const text=await r.text();if(text.length>1000000)throw Error('模型响应过大。');const content=JSON.parse(text).choices?.[0]?.message?.content;if(typeof content!=='string')throw Error('模型响应没有有效正文。');const clean=content.trim().replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,'');if(state!==activeState||state.revision!==revision||connection!==snapshot)return null;const reply=validateReply(JSON.parse(clean),state);state.ai=reply;status('AI分析已生成，推断与建议仍需您核对。');return reply;
 }catch(e){status((e.name==='AbortError'?'AI调用已取消或超时。':e.message)+' 已保留回答，可继续本地访谈。连接失败时请检查接口、密钥及CORS设置。');return null;}finally{clearTimeout(timer);busy=false;requestController=null;}
}
function disconnect(){connection=null;requestController?.abort();$('#api-key').value='';$('#model-consent').checked=false;$('#model-status').textContent='已断开，后续不再发送访谈与材料。';render();}
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function downloadReport(){download('家居AI一屏报告'+(state.accepted?'':'-讨论稿')+'.md',reportMarkdown(state),'text/markdown');}
function restore(){try{const raw=localStorage.getItem(KEY);if(!raw)throw Error('本机没有保存的新版访谈。');const s=JSON.parse(raw);if(s.version!=='0.2.0'||!QUESTIONS.every(q=>s.answers[q.id]===undefined||typeof s.answers[q.id]==='string')||!Array.isArray(s.history)||!Array.isArray(s.documents)||!s.scenes)throw Error('保存的访谈格式不兼容。');state=s;connection=null;$('#api-key').value='';closeDialogs();render();status('已恢复本机访谈，模型连接需重新设置。');}catch(e){status(e.message);closeDialogs();}}
function demo(){if(!state.demo)beforeDemo=state;state=freshInterview();state.demo=true;state.answers={role:'全屋定制工厂审单主管，向生产负责人汇报，带3人',mission:'复核订单，协调设计与拆单，最终由主管签核',handoff:'设计师提交需求、报价与订单；交付有依据的差异清单给下单员',workflow:'按订单号比对尺寸、材质、数量和版本，异常退回设计确认',capability:'熟悉工艺规则、Excel和ERP，有导出权限',kpi:'减少审单工时，漏审率不高于人工基线',idea:'AI先比对订单与报价，标记差异和原文位置',success:'手机上传文件后得到差异清单，审单员逐项确认',constraints:'只做离线试点，不自动下单；主管复核',materials:'虚构审单记录与工作规则，演示用'};state.history=QUESTIONS.map(q=>({question:q.text,answer:state.answers[q.id],round:1}));state.documents=[{id:'demo-doc',name:'虚构审单规范.txt',chunks:textChunks('审单规范（虚构）：订单与报价必须按订单号核对材质、尺寸、数量和交期。冲突项由审单主管核实，确认后才能下单。'),warnings:['模拟材料，并非真实企业数据']}];state.profileConfirmed=true;state.selected='review';const a=assessment(state);a.checks={data:'yes',rules:'yes',review:'yes',access:'yes',evidence:'yes'};a.numbers={volume:'200',before:'25',after:'10',coverage:'80',hourly:'60',cash:'0',cost:'0',setup:'0'};a.source='estimate';a.target='30';a.metric='漏审率不高于人工基线；月节省≥30小时';state.phase='report';closeDialogs();render();status('这是虚构示例：预计释放40小时/月，未将空出的工时当成工资节约。可修改数字或继续沟通。');}
$('#menu-button').onclick=()=>$('#menu-dialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#profile-button').onclick=openProfile;$('#sources-button').onclick=openSources;$('#model-button').onclick=openModel;
$('#file-input').onchange=e=>addFiles(e.target.files);$('#add-paste').onclick=()=>{const name=$('#paste-name').value.trim()||'粘贴材料',text=$('#paste-content').value.trim();if(!text){$('#material-status').textContent='请先粘贴内容。';return;}if(state.documents.length>=8){$('#material-status').textContent='最多8份材料。';return;}state.documents.push({id:uid(),name,chunks:textChunks(text),warnings:[]});$('#paste-content').value='';materialChanged();$('#material-status').textContent='已加入材料。';};
$('#connect-model').onclick=async()=>{try{const endpoint=safeEndpoint($('#endpoint').value.trim()),model=$('#model').value.trim();if(!model)throw Error('请填写模型名称。');if(!$('#model-consent').checked)throw Error('请确认允许将本轮访谈和材料发送给填写的服务。');connection={endpoint,model,key:$('#api-key').value.trim()};$('#model-dialog').close();render();status('已连接设置。接下来的回答将发送到指定服务，设置可随时断开。');}catch(e){$('#model-status').textContent=e.message;}};
$('#disconnect-model').onclick=disconnect;$('#save-button').onclick=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));status('访谈已保存到本机。');closeDialogs();}catch{status('本机存储空间不足，建议下载完整访谈。');closeDialogs();}};$('#restore-button').onclick=restore;$('#export-session').onclick=()=>download('家居AI完整访谈.json',JSON.stringify(state,null,2),'application/json');$('#demo-button').onclick=demo;$('#exit-demo').onclick=()=>{state=beforeDemo||freshInterview();beforeDemo=null;status('');render();};$('#reset-button').onclick=()=>{closeDialogs();$('#reset-dialog').showModal();};$('#confirm-reset').onclick=()=>{requestController?.abort();connection=null;state=freshInterview();beforeDemo=null;try{localStorage.removeItem(KEY);localStorage.removeItem('home-ai-opportunity-v1');}catch{}$('#api-key').value='';$('#model-consent').checked=false;closeDialogs();status('已清空。');render();};
if(document.modelContext?.registerTool){document.modelContext.registerTool({name:'read_ai_opportunity_assessment',description:'Read the current guided home furnishing AI interview, candidate conditions and one-screen report. Read only.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:args=>{if(!args||typeof args!=='object'||Array.isArray(args)||Object.keys(args).length)throw Error('Expected an empty object');return JSON.parse(JSON.stringify({version:state.version,answers:state.answers,history:state.history,candidates:candidates(state).map(s=>({id:s.id,title:s.title,assessment:judge(state,s)})),report:state.selected?report(state):null,documentCount:state.documents.length,phase:state.phase}));}});}
render();
